Q.1 For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), Find 
i. Sum of all elements 
ii. Sum of all elements row-wise 
iii. Sum of all elements column-wise 

In [1]:
import numpy as np
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print('Sum of all elements:',np.sum(gfg))
print('Row wise sum:\n',np.sum(gfg,axis=1))
print('Column wise sum: \n',np.sum(gfg,axis=0))
print()

Sum of all elements: 45
Row wise sum:
 [[14]
 [16]
 [15]]
Column wise sum: 
 [[20  9 16]]



Q.2 (a)For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
i. Sorted array 
ii. Indices of sorted array 
iii. 4 smallest elements 
iv. 5 largest elements 
(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
i. Integer elements only 
ii. Float elements only

In [2]:
import numpy as np
array=np.array([10,52,62,16,16,54,453])
print('Sorted array: ',np.sort(array))
print('Indices of sorted array: ',np.argsort(array))
print('4 smallest elements: ',np.sort(array)[0:4])
print('5 largest elements: ',np.sort(array)[-5:])

array2=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
print('Integer elements: ',array2[array2==np.floor(array2)])
print('Float elements: ',array2[array2!=np.floor(array2)])

Sorted array:  [ 10  16  16  52  54  62 453]
Indices of sorted array:  [0 3 4 1 5 2 6]
4 smallest elements:  [10 16 16 52]
5 largest elements:  [ 16  52  54  62 453]
Integer elements:  [1. 2. 3. 2.]
Float elements:  [1.2 2.2]


Q.3 You are given a weekly sales dataset and need to perform various operations 
using NumPy broadcasting. 
a) Generate your unique sales dataset: 
 Take the sum of the ASCII values of the initials of your first and last 
name. Call this value X. (If your initials are A B → ASCII sum = 65 
+ 66 = 131 → sales = [131, 181, 231, 281, 331].) 
 Create a NumPy array sales with values [X, X+50, X+100, X+150, 
X+200]. 
b) Compute your personalized tax rate as ((X % 5) + 5) / 100. 
 Use broadcasting to apply this tax rate to each sales value. 
c) Adjust sales based on discount: 
 If sales < X+100, apply a 5% discount. 
 If sales >= X+100, apply a 10% discount. 
d) Expand sales data for multiple weeks: 
 Create a 3×5 matrix representing three weeks of sales by stacking 
sales three times using broadcasting. 
 Increase sales by 2% per week using element-wise broadcasting.

In [3]:
name="HY"
sum=0
for i in name:
  sum=sum+ord(i)
print('Sum: ',sum)
sales=np.array([(sum+i*50) for i in range(0,5)])
print('Sales: ',sales)
taxrate=((sum%5)+5)/100
tax=taxrate*sales
print('Tax: ',tax)

#Apply tax
sales=tax+sales
print('Sales with tax: ',sales)
discounted=np.where(sales<(sum+100),sales*0.95,sales*0.9)
print('Sales after discount: ',discounted)

#weeksales
weeklySales=np.tile(discounted,(3,1))
increase=[[1],[1.02],[1.0404]]
print("Weekly Sales:\n",weeklySales*increase)
     

Sum:  161
Sales:  [161 211 261 311 361]
Tax:  [ 9.66 12.66 15.66 18.66 21.66]
Sales with tax:  [170.66 223.66 276.66 329.66 382.66]
Sales after discount:  [162.127 212.477 248.994 296.694 344.394]
Weekly Sales:
 [[162.127     212.477     248.994     296.694     344.394    ]
 [165.36954   216.72654   253.97388   302.62788   351.28188  ]
 [168.6769308 221.0610708 259.0533576 308.6804376 358.3075176]]


Q4. Generate x values using np.linspace() from -10 to 10 with 100 points. Use 
each function from the list below and compute y values using NumPy: 
 Y = x2 
 Y = sin(x) 
 Y = ex 
 Y = log(|x| + 1) 
Plot the chosen function using Matplotlib. Add title, labels, and grid for clarity. 

In [19]:
import matplotlib.pyplot as plt
x=np.linspace(-10,10,num=100)
y=x**2
plt.plot(x,y)
plt.title('Y=X^2')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.grid()
plt.show()
print()


y=np.sin(x)
plt.plot(x,y)
plt.title('Y=Sin(X)')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.grid()
plt.show()
print()

y=np.exp(x)
plt.plot(x,y)
plt.title('Y=e^X')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.grid()
plt.show()
print()

y=np.log(abs(x)+1)
plt.plot(x,y)
plt.title('Y=log(|x|+1)')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.grid()
plt.show()
print()

ModuleNotFoundError: No module named 'matplotlib'